import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  backgroundImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: '#transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    flexDirection: 'row',
    height: 80,
    backgroundColor: 'rgba(32, 32, 32, 0.7)',
    paddingHorizontal: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FF7777',
  },
  leftContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  rightContainer: {
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  inputContainer: {
    width: '76%',
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
  },
  input: {
    flexGrow: 1,
    paddingVertical: 20,
    borderWidth: 2,
    borderColor: '#FF7777',
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 15,
    color: 'white',
    backgroundColor: '#414141',
  },
  icon: {
    position: 'absolute',
    bottom: 37,
    right: 10,
  },

  text: {
    color: '#FF7777',
    fontSize: 36,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  textProf: {
    flexGrow: 1,
    color: '#FF7777',
    fontSize: 18,
    fontWeight: 'bold',
  },
  image: {
    width: 300,
    height: 300,
    resizeMode: 'contain',
  },
  button: {
    backgroundColor: '#6C6087',
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF7777',
    minWidth: 280,
    textAlign: 'center',
  },
  buttonMainPage: {
    backgroundColor: '#6C6087',
    paddingVertical: 8,
    paddingHorizontal: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF7777',
    minWidth: 500,
    textAlign: 'center',
    marginBottom: 10,
  },
  buttonStart: {
    backgroundColor: '#transparent',
    // paddingVertical: '100%',
    // paddingHorizontal: '100%',
    borderRadius: 0,
    borderWidth: 0,
    borderColor: '#transparent',
  },
  buttonText: {
    color: '#FF7777',
    fontSize: 14,
    fontWeight: 'bold',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    width: '75%',
    height: '25%',
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonModal: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#6C6087',
    marginBottom: 10,
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: '#FF7777',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  cameraContainer: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
  },
  camera: {
    flex: 1,
    borderRadius: 0,
  },
  cameraButton: {
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#transparent',
  },
  cameraText: {
    fontSize: 16,
    color: 'black',
    marginLeft: 10,
  },
  iconContainer: {
    position: 'absolute',
    right: 90,
    bottom: 297,
  },
  spinnerView: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#transparent',
  },
  spinner: {
    size: 'large',
  },
  list: {
    backgroundColor: '#transparent',
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF7777',
    minWidth: 250,
    marginBottom: 10,
  },
});
